const index = {
    mine_header_bg: require('./me_bg_top_nor.png'),
    mine_account_bg: require('./me_bg_account_nor.png'),
    mine_setting_icon_gray:require('./mine_setting_icon_gray.png'),
    mine_setting_icon_white:require('./mine_setting_icon_white.png'),
    mine_message_icon_gray:require('./mine_message_icon_gray.png'),
    mine_message_icon_white:require('./mine_message_icon_white.png'),
    mine_wait_pay_icon:require('./mine_wait_pay_icon.png'),
    mine_wait_send_icon:require('./mine_wait_send_icon.png'),
    mine_wait_receive_icon:require('./mine_wait_receive_icon.png'),
    mine_after_buy_icon:require('./mine_after_buy_icon.png'),
    mine_icon_invite:require('./mine_icon_invite.png'),
    mine_coupon_icon:require('./mine_coupon_icon.png'),
    mine_icon_data:require('./mine_icon_data.png'),
    mine_icon_favorite_shop:require('./mine_icon_favorite_shop.png'),
    mine_icon_help_service:require('./mine_icon_help_service.png'),
    mine_icon_address:require('./mine_icon_address.png'),
    mine_icon_notificate:require('./mine_icon_notificate.png'),
    mine_icon_mission:require('./mine_icon_mission.png'),
    mine_icon_discollect:require('./mine_icon_discollect.png'),
    mine_level_background:require('./mine_level_background.png'),
    profile_banner:require('./profile_banner.png'),
    home_jingshenqingk_bg:require('./home_jingshenqingk_bg.png'),
    home_jingshnegqingk_icon: require('./home_jingshnegqingk_icon.png'),
    mine_icon_mentor: require('./mine_icon_mentor.png'),
    mine_user_icon:require('./mine_user_icon.png'),
    mine_icon_fans:require('./mine_icon_fans.png'),
    bg_fans_item:require('./bg_fans_item.png'),
    mine_icon_message:require('./mine_icon_message.png'),
    mine_showOrder: require('./me_icon_shaidan_nor.png')
};
export default index;
