const myData = {
    ccz_03: require('./ccz_03.png'),
    jdt_05: require('./jdt_05.png'),
    black_right_arrow:require('./me_arrow.png'),
    icon_search:require('./icon_search.png'),
    icon_clean:require('./icon_clean.png'),
    icon_v0:require('./icon_v0.png'),
    icon_v1:require('./icon_v1.png'),
    icon_v2:require('./icon_v2.png'),
    icon_v3:require('./icon_v3.png'),
    icon_v4:require('./icon_v4.png'),
    icon_v5:require('./icon_v5.png'),
    next_icon:require('./next_icon.png'),
    icon_invite:require('./icon_invite.png'),
    icon_v0Bg:require('./v0Bg.png'),
    icon_v1Bg:require('./v1Bg.png'),
    icon_v2Bg:require('./v2Bg.png'),
    icon_v3Bg:require('./v3Bg.png'),
    icon_v4Bg:require('./v4Bg.png'),
    icon_v5Bg:require('./v5Bg.png'),
    icon_v0Dot:require('./VIP_V1.png'),
    icon_v1Dot:require('./VIP_V2.png'),
    icon_v2Dot:require('./VIP_V3.png'),
    icon_v3Dot:require('./VIP_V4.png'),
    icon_v4Dot:require('./VIP_V5.png'),
    icon_v5Dot:require('./VIP_V6.png'),
    icon_v0Angle:require('./AngleV0.png'),
    icon_v1Angle:require('./AngleV1.png'),
    icon_v2Angle:require('./AngleV2.png'),
    icon_v3Angle:require('./AngleV3.png'),
    icon_v4Angle:require('./AngleV4.png'),
    icon_v5Angle:require('./AngleV5.png'),
};
export default myData;
