const task = {
    task_bottom_btn: require('./task_bottom_btn.png'),
    task_box_can_open: require('./task_box_can_open.png'),
    task_box_close: require('./task_box_close.png'),
    task_box_open: require('./task_box_open.png'),
    task_progress:require('./task_progress.png'),
    task_run_people:require('./task_run_people.png'),
    task_finish:require('./task_finish.png'),
    taskModal_btn: require('./taskModal_btn.png'),
    taskModal_dou: require('./taskModal_dou.png'),
    taskModal_exp: require('./taskModal_exp.png'),
    taskModal_chou: require('./taskModal_chou.png'),
    exp_bg: require('./exp_bg.png'),
    h_bg: require('./h_bg.png'),
    dou_bg: require('./dou_bg.png'),
    chou_bg: require('./chou_bg.png'),
    taskModal_h:require('./taskModal_h.png'),
    V2:require('./V2.png'),
    V3:require('./V3.png'),
    V4:require('./V4.png'),
    V5:require('./V5.png'),
    red_btn:require('./red_btn.png'),
    yellow_btn:require('./yellow_btn.png'),
    red_bg:require('./red_bg.png'),
    gary_bg:require('./gary_bg.png'),
    current_p:require('./current_p.png'),
    taskModal_light:require('./taskModal_light.png'),
    taskModal_title:require('./taskModal_title.png'),
    inform:require('./inform.png'),
    defaultImage:require('./defaultImage.png'),
};
export default task;
