# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'crm_app_xiugou' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for crm_app_xiugou

inhibit_all_warnings!

pod 'YYKit',   '1.0.9'
pod 'AFNetworking',   '3.2.1'
pod 'SDWebImage',   '4.4.2'
pod 'TYCyclePagerView',   '1.1.0'
pod 'CocoaLumberjack', '3.4.1'
pod 'UICKeyChainStore', '2.1.1'
pod 'SandBoxPreviewTool'  ,   '1.1'  #用于实时预览沙盒文件目录
pod 'MBProgressHUD' ,   '1.1.0'
pod 'IQKeyboardManager' ,  '6.2.0'
#微信支付
pod 'WechatOpenSDK','1.8.3'
#友盟统计
pod 'UMCCommon'
pod 'UMCAnalytics', '5.5.2'
pod 'UMCSecurityPlugins'
#友盟分享

pod 'UMCShare/Social/ReducedWeChat'
pod 'UMCShare/Social/ReducedQQ'
pod 'UMCShare/Social/ReducedSina'
#七鱼
pod 'QIYU_iOS_SDK',   '4.9.0'
#极光
pod 'JPush', '3.1.0'
#神策
pod 'SensorsAnalyticsSDK', '1.10.17'
#pod 'SensorsAnalyticsSDK', :subspecs => ['ENABLE_REACT_NATIVE_APPCLICK']

##绘图和icon
#pod 'RNSVG', :path => '../node_modules/react-native-svg'
#pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
#  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'


end

#    暂时未用,先注释已被后期使用
#    pod 'UMCShare/Social', '6.9.1'
#    pod 'UMCShare/Social/QQ', '6.9.1'
#    pod 'UMCShare/Social/Sina', '6.9.1'

#    pod 'SVProgressHUD'
#    pod 'Masonry'
#    pod 'SDWebImage'
#    pod 'MJRefresh'
#    pod 'MJExtension'
#    pod 'ReactiveObjC'
#    pod 'SDCycleScrollView'
#    pod 'WZLBadge'
#    pod 'DZNEmptyDataSet'

