# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'crm_app_xiugou' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for crm_app_xiugou

inhibit_all_warnings!

pod 'YYKit',   ' 1.0.9'
pod 'AFNetworking',   '~> 3.2.1'
pod 'SDWebImage',   '~> 4.4.6'
pod 'TYCyclePagerView',   '~> 1.1.0'
pod 'CocoaLumberjack', '~> 3.4.1'
pod 'UICKeyChainStore', '~> 2.1.1'
pod 'SandBoxPreviewTool'  ,   '~> 1.1'  #用于实时预览沙盒文件目录
pod 'MBProgressHUD' ,   '~> 1.1.0'
pod 'IQKeyboardManager' ,  '~> 6.2.0'
pod 'Bugly', '~> 2.5.0'
#微信支付
pod 'WechatOpenSDK','~> 1.8.3'
#友盟统计
pod 'UMCCommon','~> 2.1.0'
pod 'UMCAnalytics','~> 6.0.5'
pod 'UMCSecurityPlugins','~> 1.0.5'
#友盟分享

pod 'UMCShare/Social/ReducedWeChat','~> 6.9.6'
pod 'UMCShare/Social/ReducedQQ','~> 6.9.6'
pod 'UMCShare/Social/ReducedSina','~> 6.9.6'
#七鱼
pod 'QIYU_iOS_SDK',   '5.2.0'
#极光
pod 'JPush',   '~> 3.2.4'
pod 'JVerification',   '~> 2.4.8'
#神策
pod 'SensorsAnalyticsSDK', '~> 1.10.17'
pod 'MJRefresh'
pod 'SDAutoLayout'
# 异步渲染
pod 'Texture' , '2.8.0'
# 分页组件
pod 'JXCategoryView','~>1.3.14'
# 阿里云视频

pod 'AliyunVideoSDKBasic','~> 3.10.5'
pod 'QuCore-ThirdParty','~> 3.10.0'
pod 'VODUpload','~> 1.5.1'
pod 'AliyunOSSiOS','~> 2.10.7'
pod 'AlivcConan','~> 0.9.5'
pod 'JSONModel','~> 1.7.0'

#pod 'SensorsAnalyticsSDK', :subspecs => ['ENABLE_REACT_NATIVE_APPCLICK']
##绘图和icon
#pod 'RNSVG', :path => '../node_modules/react-native-svg'
#pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
#  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

#  pod 'react-native-webview', :path => '../node_modules/@mr/react-native-webview'

#  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

#  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

# pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

pod 'FBLazyVector', :path => '../node_modules/react-native/Libraries/FBLazyVector'
pod 'FBReactNativeSpec', :path => '../node_modules/react-native/Libraries/FBReactNativeSpec'
pod 'RCTRequired', :path => '../node_modules/react-native/Libraries/RCTRequired'
pod 'RCTTypeSafety', :path => '../node_modules/react-native/Libraries/TypeSafety'
pod 'React', :path => '../node_modules/react-native/'
pod 'React-Core', :path => '../node_modules/react-native/'
pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
# pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
pod 'ReactCommon/jscallinvoker', :path => '../node_modules/react-native/ReactCommon'
pod 'ReactCommon/turbomodule/core', :path => '../node_modules/react-native/ReactCommon'
pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

end

#    暂时未用,先注释已被后期使用
#    pod 'UMCShare/Social', '6.9.1'
#    pod 'UMCShare/Social/QQ', '6.9.1'
#    pod 'UMCShare/Social/Sina', '6.9.1'

#    pod 'SVProgressHUD'
#    pod 'Masonry'
#    pod 'SDWebImage'
#    pod 'MJRefresh'
#    pod 'MJExtension'
#    pod 'ReactiveObjC'
#    pod 'SDCycleScrollView'
#    pod 'WZLBadge'
#    pod 'DZNEmptyDataSet'

