# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to pgyer"
  lane :to_ipa do |options|
    # 如果你没有申请adhoc证书，sigh会自动帮你申请，并且添加到Xcode里
    version = get_version_number(
      xcodeproj: "crm_app_xiugou.xcodeproj",
      target: "crm_app_xiugou"
    )
    # time = Time.new
    # timeString = (time.year).to_s + (time.month).to_s + (time.day).to_s + (time.hour).to_s + (time.min).to_s + (time.sec).to_s 
    out_name = version + '-' + options[:env] + 'sg.ipa'
    sigh(
     app_identifier: 'com.meeruu.sharegoods',
     adhoc: true
    )
    gym(
      scheme: 'crm_app_xiugou',
      workspace: 'crm_app_xiugou.xcworkspace',
      output_directory: '~/Desktop/ipa',
      output_name: out_name,
      export_options: {
        method: "ad-hoc", # 这可以不指定
      }
    )
  end
end
