# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to pgyer"
  lane :to_pgyer do
    # 如果你没有申请adhoc证书，sigh会自动帮你申请，并且添加到Xcode里
    sigh(
     app_identifier: 'com.meeruu.sharegoods',
     adhoc: true
    )
    # 以下两个action来自fastlane-plugin-versioning，
    # 第一个递增 Build，第二个设定Version。
    # 如果你有多个target，就必须指定target的值，否则它会直接找找到的第一个plist修改
    # 在这里我建议每一个打的包的Build都要不一样，这样crash了拿到日志，可以对应到ipa上
    # increment_build_number_in_plist(target: "Nursing")
    # gym用来编译ipa
    gym(
      scheme: 'crm_app_xiugou',
      workspace: 'crm_app_xiugou.xcworkspace',
      output_directory: './pgyer',
      export_options: {
        method: "ad-hoc", # 这可以不指定
      }
    )
    # 上传ipa到蒲公英服务器
    pgyer(api_key: "f8fd88e52443f483f4bb5d7dfb857e02", user_key: "0ceec8de7f57ef87ef2a7ad14bb728ab")
  end
end
