const index = {
    ccz_03: require('./ccz_03.png'),
    cs_12: require('./cs_12.png'),
    detail_benci: require('./detail_benci.png'),
    detail_cishu: require('./detail_cishu.png'),
    detail_zongti: require('./detail_zongti.png'),
    dj_03: require('./dj_03.png'),
    dy_07: require('./dy_07.png'),
    dz_03: require('./dz_03.png'),
    dzfhj_03_03: require('./dzfhj_03_03.png'),
    headBg: require('./headBg.png'),
    icon_03_02: require('./icon_03_02.png'),
    icon_03_03: require('./icon_03_03.png'),
    icon_03_04: require('./icon_03_04.png'),
    jdt_05: require('./jdt_05.png'),
    sc_03: require('./sc_03.png'),
    shezhi: require('./shezhi.png'),
    system_charge: require('./system_charge.png'),
    txbg_02: require('./txbg_02.png'),
    txbg_03: require('./txbg_03.png'),
    wsc_03: require('./wsc_03.png'),
    xjt_03: require('./xjt_03.png'),
    zje_11: require('./zje_11.png'),
    my_Shop_gengduo: require('./my_Shop_gengduo.png'),
    icon_03: require('./icon_03.png'),
    myShop_join: require('./myShop_join.png'),
    shop_box_0: require('./shop_box_0.png'),
    shop_box_25: require('./shop_box_25.png'),
    shop_box_75: require('./shop_box_75.png'),
    shop_box_100: require('./shop_box_100.png'),
    shopProduct: require('./shopProduct.png'),
    shopProductShare: require('./shopProductShare.png'),
};
export default index;
