const cashAccountImg = {
    title_card: require('./icon_card.png'),
    shuoming_icon: require('./pic_shuoming.png'),
    zhanghu_red: require('./zhanghu_hong.png'),
    zhanghu_lv: require('./zhanghu_lv.png'),
    chengFa_icon: require('./zhanghu_icon_chengfa.png'),
    daoshi_icon: require('./zhanghu_icon_daoshi.png'),
    fenhong_icon:require('./zhanghu_icon_fenhong.png'),
    fenxiang_icon:require('./zhanghu_icon_fenxiang.png'),
    hongbao_icon: require('./zhanghu_icon_hongbao.png'),
    jinggao_icon: require('./zhanghu_icon_jinggao copy.png'),
    qiandao_icon: require('./zhanghu_icon_qiandao.png'),
    other_icon:require('./zhanghu_icon_qita.png'),
    quan_icon:require('./zhanghu_icon_quan.png'),
    renwu_icon: require('./zhanghu_icon_renwu1.png'),
    renwuShuoMing_icon: require('./zhanghu_icon_renwu1.png'),
    shouru_icon: require('./zhanghu_icon_shouru.png'),
    shouyi_icon:require('./zhanghu_icon_shouyi.png'),
    tixian_icon:require('./zhanghu_icon_tixian.png'),
    tuiguang_icon: require('./zhanghu_icon_tuiguang.png'),
    xiaofei_icon: require('./zhanghu_icon_xiaofei.png'),
    zengsong_icon:require('./zhanghu_icon_zengsong.png'),
};
export default cashAccountImg;
