const testData =  {
    'shoppingCartGoodsVOS':[
        {
            'activityCode':'JF201901020049',
            'activityType':8,
            'userCode':null,
            'products':[
                {
                    'activityCode':'acode1',
                    'activityType':1,
                    'productName':'男鞋板鞋男冬季2018新款男士运动鞋白色休闲鞋小白鞋正品鞋子',
                    'specTitle':'大小@尺寸@颜色',
                    'imgUrl':'https://devcdn.sharegoodsmall.com/sharegoods/94527c6a2ab1452fb635ebb0dedfd0c8.jpg',
                    'sellStock':99,
                    'productStatus':1,
                    'propertyParam':'大小@尺寸@颜色',
                    'specifies':[
                        {
                            'paramName':'大小',
                            'paramValue':'15'
                        },
                        {
                            'paramName':'尺寸',
                            'paramValue':'15'
                        },
                        {
                            'paramName':'颜色',
                            'paramValue':'红色'
                        }
                    ],
                    'price':96,
                    'id':'5c2c857667478f24403351a8',
                    'skuCode':'SKU000001240007',
                    'spuCode':'SPU00000124',
                    'createTime':1546421622310,
                    'amount':2,
                    'buyLimit':-1,
                    'shoppingCartActivity':[
                        {
                            'prodCode':'SPU00000124',
                            'activityType':1
                        },
                        {
                            'prodCode':'SPU00000124',
                            'activityType':8
                        }
                    ]
                },
                {
                    'activityCode':'acode1',
                    'activityType':1,
                    'productName':'2018新款男士休闲裤秋冬季加绒加厚卫裤韩版潮流宽松冬款运动裤男',
                    'specTitle':'大小@尺寸@颜色',
                    'imgUrl':'https://devcdn.sharegoodsmall.com/sharegoods/e8d32c9b9d844e2f84fb10772c0b6456.jpg',
                    'sellStock':100,
                    'productStatus':1,
                    'propertyParam':'大小@尺寸@颜色',
                    'specifies':[
                        {
                            'paramName':'大小',
                            'paramValue':'15'
                        },
                        {
                            'paramName':'尺寸',
                            'paramValue':'15'
                        },
                        {
                            'paramName':'颜色',
                            'paramValue':'红色'
                        }
                    ],
                    'price':196,
                    'id':'5c2c857667478f24403351a7',
                    'skuCode':'SKU000001210001',
                    'spuCode':'SPU00000121',
                    'createTime':1546421622310,
                    'amount':2,
                    'buyLimit':-1,
                    'shoppingCartActivity':[
                        {
                            'prodCode':'SPU00000121',
                            'activityType':8
                        }
                    ]
                }
            ],
            'description':null,
            'startPrice':1,
            'startTime':1546358400000,
            'totalAmount':null,
            'startCount':1,
            'maxCount':1,
            'rules':[
                {
                    'startPrice':1,
                    'rate':1
                }
            ]
        }
    ],
    'shoppingCartFailedGoodsVOS':[
        {
            'activityCode':null,
            'activityType':null,
            'userCode':null,
            'products':[
                {
                    'activityCode':null,
                    'activityType':null,
                    'productName':'DDZY_全自动机械表防水夜光男表',
                    'specTitle':'大小@尺寸@颜色',
                    'imgUrl':'https://devcdn.sharegoodsmall.com/sharegoods/f1673aa0fd664df6ba01d718c5e444af.jpg',
                    'sellStock':9987,
                    'productStatus':1,
                    'propertyParam':'大小@尺寸@颜色',
                    'specifies':[
                        {
                            'paramName':'大小',
                            'paramValue':'15'
                        },
                        {
                            'paramName':'尺寸',
                            'paramValue':'16'
                        },
                        {
                            'paramName':'颜色',
                            'paramValue':'黄色'
                        }
                    ],
                    'price':0.1,
                    'id':'5c2dbd1c7dc05d1daa9e45de',
                    'skuCode':'SKU000001250002',
                    'spuCode':'SPU00000125',
                    'createTime':1546501404888,
                    'amount':1,
                    'buyLimit':5,
                    'shoppingCartActivity':null
                },
                {
                    'activityCode':null,
                    'activityType':null,
                    'productName':'测试wcj01',
                    'specTitle':'大小@尺寸@颜色',
                    'imgUrl':'https://devcdn.sharegoodsmall.com/sharegoods/8d2b143813d041768d081fb3e5d2bd91.jpeg',
                    'sellStock':0,
                    'productStatus':0,
                    'propertyParam':'大小@尺寸@颜色',
                    'specifies':[
                        {
                            'paramName':'大小',
                            'paramValue':'中'
                        },
                        {
                            'paramName':'尺寸',
                            'paramValue':'16'
                        },
                        {
                            'paramName':'颜色',
                            'paramValue':'蓝色'
                        }
                    ],
                    'price':8.2,
                    'id':'678',
                    'skuCode':'SKU000003270052',
                    'spuCode':'SPU00000327',
                    'createTime':1546073188000,
                    'amount':null,
                    'buyLimit':-1,
                    'shoppingCartActivity':null
                }
            ],
            'description':null,
            'startPrice':null,
            'startTime':null,
            'totalAmount':null,
            'startCount':null,
            'maxCount':null,
            'rules':null
        },
        {
            'activityCode':null,
            'activityType':null,
            'userCode':null,
            'products':[
                {
                    'activityCode':null,
                    'activityType':null,
                    'productName':'DDZY_全自动机械表防水夜光男表',
                    'specTitle':'大小@尺寸@颜色',
                    'imgUrl':'https://devcdn.sharegoodsmall.com/sharegoods/f1673aa0fd664df6ba01d718c5e444af.jpg',
                    'sellStock':9987,
                    'productStatus':1,
                    'propertyParam':'大小@尺寸@颜色',
                    'specifies':[
                        {
                            'paramName':'大小',
                            'paramValue':'15'
                        },
                        {
                            'paramName':'尺寸',
                            'paramValue':'16'
                        },
                        {
                            'paramName':'颜色',
                            'paramValue':'黄色'
                        }
                    ],
                    'price':0.1,
                    'id':'5c2dbd1c7dc05d1daa9e45de',
                    'skuCode':'SKU000001250002',
                    'spuCode':'SPU00000125',
                    'createTime':1546501404888,
                    'amount':1,
                    'buyLimit':5,
                    'shoppingCartActivity':null
                },
                {
                    'activityCode':null,
                    'activityType':null,
                    'productName':'测试wcj01',
                    'specTitle':'大小@尺寸@颜色',
                    'imgUrl':'https://devcdn.sharegoodsmall.com/sharegoods/8d2b143813d041768d081fb3e5d2bd91.jpeg',
                    'sellStock':0,
                    'productStatus':0,
                    'propertyParam':'大小@尺寸@颜色',
                    'specifies':[
                        {
                            'paramName':'大小',
                            'paramValue':'中'
                        },
                        {
                            'paramName':'尺寸',
                            'paramValue':'16'
                        },
                        {
                            'paramName':'颜色',
                            'paramValue':'蓝色'
                        }
                    ],
                    'price':8.2,
                    'id':'678',
                    'skuCode':'SKU000003270052',
                    'spuCode':'SPU00000327',
                    'createTime':1546073188000,
                    'amount':null,
                    'buyLimit':-1,
                    'shoppingCartActivity':null
                }
            ],
            'description':null,
            'startPrice':null,
            'startTime':null,
            'totalAmount':null,
            'startCount':null,
            'maxCount':null,
            'rules':null
        }
    ]
}

export default testData;
