const MineModular = {

    'ViewPersonalInfo':{
        'des':'查看个人资料',
        'name':'ViewPersonalInfo',
        'params':{}
    },
    'ViewLevelInterest':{
        'des':'查看等级权益',
        'name':'ViewLevelInterest',
        'params':{}
    },
    'ViewHowTo':{
        'des':'点击查看“如何玩转秀购”',
        'name':'ViewHowTo',
        'params':{}
    },
    'ViewAccountBalance':{
        'des':'点击查看账户余额',
        'name':'ViewAccountBalance',
        'params':{}
    },
    'ViewShowDou':{
        'des':'点击查看秀豆',
        'name':'ViewShowDou',
        'params':{}
    },
    'ViewWaitToRecord':{
        'des':'点击查看待入帐',
        'name':'ViewWaitToRecord',
        'params':{}
    },
    'ViewCoupon':{
        'des':'点击查看优惠券',
        'name':'ViewCoupon',
        'params':{}
    },
    'ViewMyInfos':{
        'des':'点击查看我的资料',
        'name':'ViewMyInfos',
        'params':{}
    },
    'ViewMyPinCollection':{
        'des':'点击查看收藏店铺',
        'name':'ViewMyPinCollection',
        'params':{}
    },
    'ViewMyXiuCollection':{
        'des':'点击查看秀场收藏',
        'name':'ViewMyXiuCollection',
        'params':{}
    },
    'ViewMyFans':{
        'des':'点击查看我的秀迷',
        'name':'ViewMyFans',
        'params':{}
    },
    'ViewMyAdviser':{
        'des':'点击查看服务顾问',
        'name':'ViewMyAdviser',
        'params':{}
    },
    'ClickCustomerService':{
        'des':'点击帮助与客服',
        'name':'ClickCustomerService',
        'params':{}
    },
    'ClickContactCustomerService':{
        'des':'点击联系客服',
        'name':'ClickContactCustomerService',
        'params':{}
    }
};

export default MineModular
