//秀场埋点
const ShowModular = {
    "ShowBannerRecommandClick":{
        "des":'秀场banner推荐图展示',
        "name":"ShowBannerRecommandClick",
        "params":{}
    },
    "ShowBannerClick":{
        "des":'秀场banner推荐图点击',
        "name":"ShowBannerClick",
        "params":{}
    },
    "WatchXiuChang":{
        "des":'浏览秀场-精选热门/最新秀场',
        "name":"ViewXiuChang",
        "params":{}
    },
    "XiuChangDetails":{
        "des":'秀场文章详情查看',
        "name":"XiuChangDetails",
        "params":{}
    },
    "ArticleShare":{
        "des":'文章分享',
        "name":"ArticleShare",
        "params":{}
    },
    "CollectingArticle":{
        "des":'文章收藏',
        "name":"CollectingArticle",
        "params":{}
    },
    "CancelArticleCollection":{
        "des":'文章取消收藏',
        "name":"CancelArticleCollection",
        "params":{}
    },
}

export default ShowModular
